;;; minuet-capf-tests.el --- Tests for Minuet CAPF -*- lexical-binding: t; -*-

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'minuet-capf)

(defvar company-backend nil)
(defvar company--capf-cache nil)
(defvar completion-all-sorted-completions nil)
(defvar corfu--input nil)

(defun minuet-capf-tests--wait (&optional seconds)
  "Wait SECONDS while allowing timers to run."
  (let ((deadline (+ (float-time) (or seconds 0.1))))
    (while (< (float-time) deadline)
      (sit-for 0.01))))

(defun minuet-capf-tests--dispatch-session ()
  "Manually dispatch the current CAPF session in batch tests."
  (when minuet-capf--session
    (minuet-capf--dispatch-request (current-buffer) minuet-capf--session)))

(defun minuet-capf-tests--cache-anchors ()
  "Return cached request anchors from newest to oldest."
  (mapcar #'minuet-capf--cache-entry-anchor minuet-capf--cache))

(ert-deftest minuet-capf-returns-point-range-and-props ()
  (with-temp-buffer
    (insert "foo")
    (let ((minuet-provider 'openai-fim-compatible))
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t)))
        (let ((capf (minuet-completion-at-point)))
          (should (equal (list (nth 0 capf) (nth 1 capf))
                         (list (point) (point))))
          (should (functionp (nth 2 capf)))
          (should (eq (plist-get (nthcdr 3 capf) :exclusive) 'no))
          (should (functionp (plist-get (nthcdr 3 capf) :exit-function))))))))

(ert-deftest minuet-capf-cache-miss-returns-immediately-then-fills-cache ()
  (with-temp-buffer
    (let ((minuet-provider 'openai-fim-compatible)
          (minuet-add-single-line-entry nil)
          (minuet-capf-debounce-delay 0)
          (minuet-capf-throttle-delay 0)
          request-count)
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t))
                ((symbol-function 'minuet--openai-fim-compatible-complete)
                 (lambda (_context callback)
                   (setq request-count (1+ (or request-count 0)))
                   (run-at-time 0 nil
                                (lambda ()
                                  (funcall callback '("alpha" "beta" "alpha")))))))
        (let* ((capf (minuet-completion-at-point))
               (table (nth 2 capf)))
          (should-not (all-completions "" table))
          (should (eq (minuet-capf--state-status minuet-capf--session)
                      'scheduled))
          (should (= (or request-count 0) 0))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait)
          (should (= request-count 1))
          (should (equal (all-completions "a" table) '("alpha")))
          (should (equal (funcall table "" nil 'metadata)
                         '(metadata (category . minuet-capf))))
          (should-not (funcall table "" nil 'boundaries)))))))

(ert-deftest minuet-capf-debounce-coalesces-repeated-table-queries ()
  (with-temp-buffer
    (let ((minuet-provider 'openai-fim-compatible)
          (minuet-capf-debounce-delay 0.03)
          (minuet-capf-throttle-delay 0)
          request-count)
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t))
                ((symbol-function 'minuet--openai-fim-compatible-complete)
                 (lambda (_context callback)
                   (setq request-count (1+ (or request-count 0)))
                   (funcall callback '("alpha")))))
        (let* ((capf (minuet-completion-at-point))
               (table (nth 2 capf)))
          (should-not (all-completions "" table))
          (should-not (all-completions "" table))
          (should (eq (minuet-capf--state-status minuet-capf--session)
                      'scheduled))
          (should (= (or request-count 0) 0))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait 0.08)
          (should (= request-count 1))
          (should (equal (all-completions "" table) '("alpha"))))))))

(ert-deftest minuet-capf-throttle-delays-followup-request ()
  (with-temp-buffer
    (let ((minuet-provider 'openai-fim-compatible)
          (minuet-capf-debounce-delay 0)
          (minuet-capf-throttle-delay 0.2)
          request-count)
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t))
                ((symbol-function 'minuet--openai-fim-compatible-complete)
                 (lambda (_context callback)
                   (setq request-count (1+ (or request-count 0)))
                   (funcall callback (list (format "item-%s" request-count))))))
        (let* ((capf-1 (minuet-completion-at-point))
               (table-1 (nth 2 capf-1))
               capf-2 table-2)
          (should-not (all-completions "" table-1))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait 0.05)
          (should (= request-count 1))
          (insert "x")
          (setq capf-2 (minuet-completion-at-point))
          (setq table-2 (nth 2 capf-2))
          (should-not (all-completions "" table-2))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait 0.05)
          (should (= request-count 1))
          (minuet-capf-tests--wait 0.25)
          (should (= request-count 2))
          (should (equal (all-completions "" table-2) '("item-2"))))))))

(ert-deftest minuet-capf-callback-trims-text-typed-after-request-start ()
  (with-temp-buffer
    (let ((minuet-provider 'openai-fim-compatible)
          (minuet-add-single-line-entry nil)
          (minuet-capf-debounce-delay 0)
          (minuet-capf-throttle-delay 0)
          callback)
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t))
                ((symbol-function 'minuet--openai-fim-compatible-complete)
                 (lambda (_context cb)
                   (setq callback cb))))
        (let* ((capf (minuet-completion-at-point))
               (table (nth 2 capf)))
          (should-not (all-completions "" table))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait)
          (insert "al")
          (funcall callback '("alpha" "beta"))
          (should (equal (all-completions "" table) '("pha"))))))))

(ert-deftest minuet-capf-company-refresh-is-triggered-on-callback ()
  (with-temp-buffer
    (let ((minuet-provider 'openai-fim-compatible)
          (minuet-capf-debounce-delay 0)
          (minuet-capf-throttle-delay 0)
          (company-backend 'company-capf)
          (company--capf-cache 'stale)
          callback
          refreshed)
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t))
                ((symbol-function 'minuet--openai-fim-compatible-complete)
                 (lambda (_context cb)
                   (setq callback cb)))
                ((symbol-function 'company--active-p)
                 (lambda () t))
                ((symbol-function 'company--perform)
                 (lambda ()
                   (setq refreshed t))))
        (let* ((capf (minuet-completion-at-point))
               (table (nth 2 capf)))
          (should-not (all-completions "" table))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait)
          (funcall callback '("alpha"))
          (should refreshed)
          (should-not company--capf-cache)
          (should (equal (all-completions "" table) '("alpha"))))))))

(ert-deftest minuet-capf-corfu-refresh-invalidates-stale-input-and-cache ()
  (with-temp-buffer
    (let ((completion-in-region-mode t)
          (corfu-mode t)
          (corfu--input '("foo" . 3))
          (completion-all-sorted-completions '("stale"))
          seen-input
          seen-cache)
      (cl-letf (((symbol-function 'corfu--exhibit)
                 (lambda ()
                   (setq seen-input corfu--input
                         seen-cache completion-all-sorted-completions))))
        (minuet-capf--refresh-frontends)
        (should-not seen-input)
        (should-not seen-cache)
        (should-not completion-all-sorted-completions)))))

(ert-deftest minuet-capf-stale-callback-is-ignored-after-flush ()
  (with-temp-buffer
    (let ((minuet-provider 'openai-fim-compatible)
          (minuet-capf-debounce-delay 0)
          (minuet-capf-throttle-delay 0)
          callback)
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t))
                ((symbol-function 'minuet--openai-fim-compatible-complete)
                 (lambda (_context cb)
                   (setq callback cb))))
        (let* ((capf (minuet-completion-at-point))
               (table (nth 2 capf)))
          (should-not (all-completions "" table))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait)
          (minuet-capf--flush-session)
          (funcall callback '("late"))
          (should-not minuet-capf--session)
          (should-not (all-completions "" table)))))))

(ert-deftest minuet-capf-reuses-request-cache-with-range ()
  (with-temp-buffer
    (let ((minuet-provider 'openai-fim-compatible)
          (minuet-add-single-line-entry nil)
          (minuet-capf-debounce-delay 0)
          (minuet-capf-throttle-delay 0)
          request-count)
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t))
                ((symbol-function 'minuet--openai-fim-compatible-complete)
                 (lambda (_context callback)
                   (setq request-count (1+ (or request-count 0)))
                   (funcall callback '("alpha")))))
        (let* ((capf-1 (minuet-completion-at-point))
               (table-1 (nth 2 capf-1)))
          (should-not (all-completions "" table-1))
          (minuet-capf-tests--dispatch-session)
          (minuet-capf-tests--wait)
          (should (= request-count 1))
          (should (= (length minuet-capf--cache) 1))
          (insert "al")
          (let* ((capf-2 (minuet-completion-at-point))
                 (table-2 (nth 2 capf-2)))
            (should (equal (list (nth 0 capf-2) (nth 1 capf-2))
                           (list (point-min) (point))))
            (should (= (length minuet-capf--cache) 1))
            (should (equal (all-completions "al" table-2) '("alpha")))
            (should (= request-count 1))))))))

(ert-deftest minuet-capf-prunes-invalidated-cache-entries ()
  (with-temp-buffer
    (insert "zz")
    (setq-local minuet-capf--cache
                (list (minuet-capf--cache-entry-create
                       :anchor (point-min)
                       :candidates '("alpha"))))
    (let ((minuet-provider 'openai-fim-compatible))
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t)))
        (let ((capf (minuet-completion-at-point)))
          (should (equal (list (nth 0 capf) (nth 1 capf))
                         (list (point) (point))))
          (should-not minuet-capf--cache))))))

(ert-deftest minuet-capf-prefers-newest-valid-cache-entry ()
  (with-temp-buffer
    (insert "al")
    (setq-local minuet-capf--cache
                (list (minuet-capf--cache-entry-create
                       :anchor (1+ (point-min))
                       :candidates '("lpha"))
                      (minuet-capf--cache-entry-create
                       :anchor (point-min)
                       :candidates '("alpha"))))
    (let ((minuet-provider 'openai-fim-compatible))
      (cl-letf (((symbol-function 'minuet--openai-fim-compatible-available-p)
                 (lambda () t)))
        (let* ((capf (minuet-completion-at-point))
               (table (nth 2 capf)))
          (should (equal (list (nth 0 capf) (nth 1 capf))
                         (list (1+ (point-min)) (point))))
          (should (equal (all-completions "l" table) '("lpha"))))))))

(ert-deftest minuet-capf-cache-is-capped ()
  (with-temp-buffer
    (dotimes (index 10)
      (minuet-capf--store-cache
       (+ (point-min) index)
       (list (format "item-%s" index))))
    (should (= (length minuet-capf--cache) minuet-capf--max-cache-size))
    (should (equal (minuet-capf-tests--cache-anchors)
                   '(10 9 8 7 6 5 4 3)))))

(provide 'minuet-capf-tests)
;;; minuet-capf-tests.el ends here
